---
title: "GWAS on gypsy moths results"
output: html_notebook
---

# Results

You'll find the results in three separate Excel workbooks:

- [GWAS-Mass-results.xlsx](http://darwin.eeb.uconn.edu/eeb348-resources/GWAS-Mass-results.xlsx)
- [GWAS-PD-results.xlsx](http://darwin.eeb.uconn.edu/eeb348-resources/GWAS-PD-results.xlsx)
- [GWAS-TDT-results.xlsx](http://darwin.eeb.uconn.edu/eeb348-resources/GWAS-TDT-results.xlsx)

# Running the analyses

If you're interested in how I ran the analyses, you'll find the code in [GWAS.r](http://darwin.eeb.uconn.edu/eeb348-resources/GWAS.r). Just put the code in the same directory as `gypsymoth.csv` and type `source("GWAS.r")` at the command prompt in an `R` console. It will churn for a day or a day and a half and put three CSV files in your working directory. The Excel workbooks come from opening the CSV files and adding a little formatting.

If I'd had a bit more time, I could have written a version of `GWAS.r` that ran the analyses much more quickly, but getting that right would have taken more time than simply running the crude version linked here.

# Genomic prediction

If you want to see what a crude approach to genomic prediction looks like with the gypsymoth data, refer to [genomic-prediction.nb.html](genomic-prediction.nb.html) ([Rmd version](genomic-prediction.Rmd))
