---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ape)
library(phyclust)
library(tidyverse)
```

24 ADH sequences from Genbank. Aligned using default parameters in Muscle [https://www.ebi.ac.uk/Tools/services/web_muscle/toolform.ebi](https://www.ebi.ac.uk/Tools/services/web_muscle/toolform.ebi)

```{r}
adh <- read.dna("Drosophila-ADH-aligned.clw", format = "clustal")
rownames(adh) <- paste("Seq", 1:nrow(adh), sep = "")
adh_distances <- dist.dna(adh)
adh_tree <- nj(adh_distances)
plot(adh_tree)
adh_trimmed <- drop.tip(adh_tree, c(22, 19, 17, 16, 14, 23, 20, 18, 12, 24, 3:6, 21, 13, 15, 8, 2))
plot(adh_trimmed)
adh_chrono <- chronos(adh_trimmed)
plot(adh_chrono)
nodelabels()

n_reps <- 1000
n_taxa <- length(adh_chrono$tip.label)
coal_times <- matrix(nrow = n_reps, ncol = n_taxa - 1)
for (i in 1:n_reps) {
  ms_out <- ms(nsam = n_taxa, opts = "-T")
  ms_tree <- read.tree(text = ms_out)
  coal_times[i, ] <- branching.times(ms_tree)
  for (j in 1:(n_taxa - 1)) {
    coal_times[i, j] <- coal_times[i, j]/coal_times[i, 1]
  }
}
result <- data.frame(Observed = branching.times(adh_chrono),
                     Expected = apply(coal_times, 2, mean),
                     Lower_2.5 = apply(coal_times, 2, quantile, 0.025),
                     Upper_97.5 = apply(coal_times, 2, quantile, 0.975))
result
for_plot <- data.frame(t(cbind(branching.times(adh_chrono), t(coal_times))))
colnames(for_plot) <- c(paste("Node", (n_taxa+1):(2*n_taxa-1), sep = ""))
for_plot$Replicate <- paste(rep("Replicate", nrow(for_plot), sep = ""))
for_plot <- for_plot %>%
  pivot_longer(starts_with("Node"), values_to = "Time") %>%
  filter(name != paste("Node", n_taxa+1, sep = ""))
p <- ggplot(for_plot, aes(x = name, y = Time)) +
  geom_violin() +
  xlab("Observed time of coalescence") +
  ylab("Expected time of coalescence") + 
  theme_bw()
p
p <- ggplot(result, aes(x = Expected, y = Observed)) +
  geom_point() +
  geom_errorbar(aes(xmin = Lower_2.5, xmax = Upper_97.5)) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_bw()
p
```


13 sRNAse sequences from *Solanum carolinense*. Aligned using default parameters in Muscle [https://www.ebi.ac.uk/Tools/services/web_muscle/toolform.ebi](https://www.ebi.ac.uk/Tools/services/web_muscle/toolform.ebi) 

See Richman et al. (1995) doi: [10.1038/hdy.1995.153](https://dx.doi.org/10.1038/hdy.1995.153)

```{r}
rnase <- read.dna("sRNAse-Solanum-carolinense.clw", format = "clustal")
rownames(rnase) <- paste("Seq", 1:nrow(rnase), sep = "")
rnase_distances <- dist.dna(rnase)
rnase_tree <- nj(rnase_distances)
plot(rnase_tree)
rnase_trimmed <- drop.tip(rnase_tree, c(5, 11))
rnase_chrono <- chronos(rnase_trimmed, model = "relaxed")
plot(rnase_chrono)
nodelabels()

n_reps <- 1000
n_taxa <- length(rnase_chrono$tip.label)
coal_times <- matrix(nrow = n_reps, ncol = n_taxa - 1)
for (i in 1:n_reps) {
  ms_out <- ms(nsam = n_taxa, opts = "-T")
  ms_tree <- read.tree(text = ms_out)
  coal_times[i, ] <- branching.times(ms_tree)
  for (j in 1:(n_taxa - 1)) {
    coal_times[i, j] <- coal_times[i, j]/coal_times[i, 1]
  }
}
plot(ms_tree)
nodelabels()
result <- data.frame(Observed = branching.times(rnase_chrono),
                     Expected = apply(coal_times, 2, mean),
                     Lower_2.5 = apply(coal_times, 2, quantile, 0.025),
                     Upper_97.5 = apply(coal_times, 2, quantile, 0.975))
result
p <- ggplot(result, aes(x = Expected, y = Observed)) +
  geom_point() +
  geom_errorbar(aes(xmin = Lower_2.5, xmax = Upper_97.5)) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_bw()
p

rnase_trimmed <- drop.tip(rnase_tree, c(6, 7, 8, 9))
rnase_chrono <- chronos(rnase_trimmed, model = "relaxed")
plot(rnase_chrono)
nodelabels()

n_reps <- 1000
n_taxa <- length(rnase_chrono$tip.label)
coal_times <- matrix(nrow = n_reps, ncol = n_taxa - 1)
for (i in 1:n_reps) {
  ms_out <- ms(nsam = n_taxa, opts = "-T")
  ms_tree <- read.tree(text = ms_out)
  coal_times[i, ] <- branching.times(ms_tree)
  for (j in 1:(n_taxa - 1)) {
    coal_times[i, j] <- coal_times[i, j]/coal_times[i, 1]
  }
}
plot(ms_tree)
nodelabels()
result <- data.frame(Observed = branching.times(rnase_chrono),
                     Expected = apply(coal_times, 2, mean),
                     Lower_2.5 = apply(coal_times, 2, quantile, 0.025),
                     Upper_97.5 = apply(coal_times, 2, quantile, 0.975))
result
p <- ggplot(result, aes(x = Expected, y = Observed)) +
  geom_point() +
  geom_errorbar(aes(xmin = Lower_2.5, xmax = Upper_97.5)) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_bw()
p

rnase_trimmed <- drop.tip(rnase_tree, c(4, 5, 10, 11, 12))
rnase_chrono <- chronos(rnase_trimmed, model = "relaxed")
plot(rnase_chrono)
nodelabels()

n_reps <- 1000
n_taxa <- length(rnase_chrono$tip.label)
coal_times <- matrix(nrow = n_reps, ncol = n_taxa - 1)
for (i in 1:n_reps) {
  ms_out <- ms(nsam = n_taxa, opts = "-T")
  ms_tree <- read.tree(text = ms_out)
  coal_times[i, ] <- branching.times(ms_tree)
  for (j in 1:(n_taxa - 1)) {
    coal_times[i, j] <- coal_times[i, j]/coal_times[i, 1]
  }
}
plot(ms_tree)
nodelabels()
result <- data.frame(Observed = branching.times(rnase_chrono),
                     Expected = apply(coal_times, 2, mean),
                     Lower_2.5 = apply(coal_times, 2, quantile, 0.025),
                     Upper_97.5 = apply(coal_times, 2, quantile, 0.975))
result
p <- ggplot(result, aes(x = Expected, y = Observed)) +
  geom_point() +
  geom_errorbar(aes(xmin = Lower_2.5, xmax = Upper_97.5)) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_bw()
p
```